# http port set
server:
  port: 8518
  
# Oracle Connect
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
# ORM JPA
  jpa:  
    hibernate:
      ddl-auto : none
      
# View resolver(Templete ->JSP Use)    
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix: .jsp
# DEVTOOLS
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      
# gmail Transfer     
  mail:
    host: smtp.gmail.com
    port: 587
    username: dmstn18120@gmail.com
    password: gozldsh860
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
      
  
# Mybatis
mybatis:
  # dto Location
  type-aliases-package: com.oracle.sBootMybatis03.model   
  # XML Location
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml

  